---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mysql-operator
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  labels:
    app.kubernetes.io/name: mysql-operator
    app.kubernetes.io/part-of: management
spec:
  project: default
  source:
    path: kustomize/overlays/docker-server
    repoURL: https://github.com/jayamorin/mysql-operator.git
    targetRevision: develop
  destination:
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true
  revisionHistoryLimit: 10
